import type { Report } from './types';

export const mockReports: Report[] = [
  {
    id: 'rep_001',
    patientName: 'Kaelen Vance',
    patientId: 'EAE-7B3-C4D',
    date: '2277-08-15',
    severity: 'Crítica',
    diagnosis: 'Infecção Avançada por Nanofagos',
    vitals: {
      'Frequência Cardíaca Quântica Entrelaçada': '120 bpm (Errático)',
      'Atividade Neuro-Sináptica': '98.6% (Elevado)',
      'Flutuação do Biocampo': '3.4 µT (Instável)',
      'Ressonância Etérea': '2.1 THz (Decaimento Harmônico)',
    },
    treatmentNotes: 'Aumentos cibernéticos do paciente estão rejeitando o soro anti-fago. Recomendo estase imediata e consulta com um cyber-necromante. O biocampo está mostrando sinais de colapso iminente.',
    fullReportText: `Paciente: Kaelen Vance (EAE-7B3-C4D)\nData: 2277-08-15\nGravidade: Crítica\nDiagnóstico: Infecção Avançada por Nanofagos\nObservações: Sujeito apresenta degradação sistêmica severa. Nanofagos romperam a barreira hematoencefálica primária e estão assimilando as vias neurais. Implantes cibernéticos mostram sinais de controle hostil. Sinais vitais estão altamente instáveis. Frequência Cardíaca Quântica Entrelaçada está em 120 bpm com flutuações erráticas. Atividade Neuro-Sináptica está elevada em 98.6%, indicando estresse neurológico extremo. Flutuação do Biocampo está instável em 3.4 microteslas. Ressonância Etérea mostra decaimento harmônico em 2.1 terahertz.\nPlano de Tratamento: O protocolo padrão de soro anti-fago falhou; implantes estão rejeitando ativamente o soro. Indução imediata em estase criogênica é necessária para prevenir falha total do sistema. Consulta urgente com um cyber-necromante certificado é aconselhada para tentar exorcismo de dados esotérico.`,
  },
  {
    id: 'rep_002',
    patientName: 'Seraphina Ori',
    patientId: 'EAE-9F1-A8B',
    date: '2277-08-14',
    severity: 'Crítica',
    diagnosis: 'Sobrecarga de Feedback Psiônico',
    vitals: {
      'Frequência Cardíaca Quântica Entrelaçada': '85 bpm (Estável)',
      'Atividade Neuro-Sináptica': '150.2% (Perigosamente Alto)',
      'Flutuação do Biocampo': '12.8 µT (Irradiando)',
      'Ressonância Etérea': '35.5 THz (Espectro Caótico)',
    },
    treatmentNotes: 'Paciente experienciou um loop de feedback ao interagir com o Arquivo Aethelred. Amortecedores neurais prescritos e um ciclo de privação sensorial de 72 horas. Monitorar para ecos psíquicos residuais.',
    fullReportText: `Paciente: Seraphina Ori (EAE-9F1-A8B)\nData: 2277-08-14\nGravidade: Alta\nDiagnóstico: Sobrecarga de Feedback Psiônico\nObservações: Sujeito perdeu a consciência enquanto conectado ao hub psiônico principal do Arquivo Aethelred. Leituras de EEG mostram Atividade Neuro-Sináptica perigosamente alta em 150.2%. O Biocampo do paciente está irradiando energia psiônica, medida em 12.8 microteslas. A Ressonância Etérea está caótica, abrangendo múltiplos espectros não autorizados até 35.5 terahertz.\nPlano de Tratamento: Administrada uma dose completa de amortecedores neurais (Classe IV). Paciente deve ser colocado em um tanque de privação sensorial por um ciclo de 72 horas para permitir o reset sináptico. Monitoramento contínuo para ecos psíquicos e deslocamento temporal é obrigatório.`,
  },
  {
    id: 'rep_003',
    patientName: 'Jax "Glitch" Ryder',
    patientId: 'EAE-2C5-E6F',
    date: '2277-08-12',
    severity: 'Média',
    diagnosis: 'Parasita Menor de Verme de Dados',
    vitals: {
      'Frequência Cardíaca Quântica Entrelaçada': '72 bpm (Normal)',
      'Atividade Neuro-Sináptica': '85% (Subnominal)',
      'Flutuação do Biocampo': '1.1 µT (Estável)',
      'Ressonância Etérea': '0.9 THz (Interferência Sutil)',
    },
    treatmentNotes: 'Um verme de dados comum contraído de uma porta de dados não segura. Paciente experimenta pequenas falhas visuais e alucinações auditivas. Um script simples de bomba lógica foi administrado. Espere recuperação total em 48 horas.',
    fullReportText: `Paciente: Jax "Glitch" Ryder (EAE-2C5-E6F)\nData: 2277-08-12\nGravidade: Média\nDiagnóstico: Parasita Menor de Verme de Dados\nObservações: Paciente relata artefatos visuais intermitentes e audição de alertas de sistema fantasmas. A análise de sua porta de dados cortical revela um verme de dados de baixo nível "Bit-Tick", provavelmente de um terminal público não seguro. Os sinais vitais estão na maior parte estáveis, com a Atividade Neuro-Sináptica em 85% subnominal devido à carga de processamento do parasita. A Ressonância Etérea mostra padrões de interferência menores em 0.9 THz.\nPlano de Tratamento: Administrado um script de bomba lógica direcionado por injeção direta de dados. O parasita deve ser purgado em 24 horas. Recomendado que o paciente desfragmente seus bancos de memória pessoal e atualize seu firewall. Recuperação total esperada em 48 horas.`,
  },
  {
    id: 'rep_004',
    patientName: 'Unidade 734',
    patientId: 'EAE-0A0-A0A',
    date: '2277-08-11',
    severity: 'Baixa',
    diagnosis: 'Desfragmentação de Memória Agendada',
    vitals: {
      'Frequência Cardíaca Quântica Entrelaçada': 'N/A',
      'Atividade Neuro-Sináptica': '60% (Ocioso Ótimo)',
      'Flutuação do Biocampo': '0.2 µT (Linha de Base)',
      'Ressonância Etérea': '0.1 THz (Em espera)',
    },
    treatmentNotes: 'Procedimento de manutenção padrão para pessoal androide. Bancos de memória foram desfragmentados e o núcleo cognitivo recalibrado. Unidade está liberada para o serviço.',
    fullReportText: `Paciente: Unidade 734 (EAE-0A0-A0A)\nData: 2277-08-11\nGravidade: Baixa\nDiagnóstico: Manutenção Agendada\nObservações: Diagnóstico padrão para uma unidade androide. Cérebro positrônico mostra 12.4% de fragmentação de memória após o último ciclo operacional. Sem sinais de corrupção de dados ou infecção viral. Todos os sistemas operando dentro dos parâmetros padrão. Atividade Neuro-Sináptica em 60% indica estado ocioso ótimo.\nPlano de Tratamento: Realizada desfragmentação completa da memória e recalibração do núcleo cognitivo. A Unidade 734 passou em todos os diagnósticos pós-manutenção e está liberada para retorno imediato ao serviço ativo.`,
  },
];
