import type { Report } from './types';

export const mockReports: Report[] = [
  {
    id: 'rep_001',
    patientName: 'Carlos Almeida',
    patientId: 'SUS-7B3-C4D',
    date: '2024-07-28',
    severity: 'Crítica',
    diagnosis: 'Infarto Agudo do Miocárdio',
    vitals: {
      'Frequência Cardíaca': '110 bpm',
      'Pressão Arterial': '160/100 mmHg',
      'Temperatura Corporal': '37.1°C',
      'Saturação de Oxigênio': '92%',
    },
    treatmentNotes: 'Paciente admitido com dor torácica intensa. Eletrocardiograma confirma IAM. Iniciado protocolo de emergência com aspirina, clopidogrel e morfina. Encaminhado para cateterismo.',
    fullReportText: `Paciente: Carlos Almeida (SUS-7B3-C4D)\nData: 2024-07-28\nGravidade: Crítica\nDiagnóstico: Infarto Agudo do Miocárdio\nObservações: Paciente, 58 anos, masculino, com histórico de hipertensão e tabagismo, apresentou dor precordial opressiva com irradiação para o membro superior esquerdo há 2 horas. Sudorese intensa e dispneia.\nSinais Vitais: FC: 110 bpm, PA: 160/100 mmHg, Temp: 37.1°C, SpO2: 92% em ar ambiente.\nPlano de Tratamento: Administrado AAS 300mg, Clopidogrel 300mg, Morfina 2mg IV. Solicitado exames laboratoriais de urgência (marcadores de necrose miocárdica). Paciente encaminhado para unidade de hemodinâmica para angioplastia primária.`,
  },
  {
    id: 'rep_002',
    patientName: 'Fernanda Costa',
    patientId: 'SUS-9F1-A8B',
    date: '2024-07-27',
    severity: 'Alta',
    diagnosis: 'Crise Aguda de Asma',
    vitals: {
      'Frequência Cardíaca': '125 bpm',
      'Pressão Arterial': '130/85 mmHg',
      'Temperatura Corporal': '36.8°C',
      'Saturação de Oxigênio': '89%',
    },
    treatmentNotes: 'Paciente com dispneia severa e sibilância audível. Administrado Salbutamol via nebulização e corticoide intravenoso. Saturação melhorou após intervenção.',
    fullReportText: `Paciente: Fernanda Costa (SUS-9F1-A8B)\nData: 2024-07-27\nGravidade: Alta\nDiagnóstico: Crise Aguda de Asma\nObservações: Paciente, 25 anos, feminina, asmática conhecida, chegou ao pronto-socorro com quadro de dispneia intensa, uso de musculatura acessória e sibilância difusa bilateral. Relata ter esquecido de usar sua medicação de controle.\nSinais Vitais: FC: 125 bpm, PA: 130/85 mmHg, Temp: 36.8°C, SpO2: 89%.\nPlano de Tratamento: Realizada nebulização com Salbutamol (3 ciclos). Administrado Hidrocortisona 200mg IV. Monitorização contínua da oximetria de pulso. Paciente apresentou melhora clínica significativa e aumento da saturação para 95%. Manter em observação.`,
  },
  {
    id: 'rep_003',
    patientName: 'José Oliveira',
    patientId: 'SUS-2C5-E6F',
    date: '2024-07-27',
    severity: 'Média',
    diagnosis: 'Gastroenterite Viral',
    vitals: {
      'Frequência Cardíaca': '95 bpm',
      'Pressão Arterial': '110/70 mmHg',
      'Temperatura Corporal': '38.5°C',
      'Saturação de Oxigênio': '98%',
    },
    treatmentNotes: 'Paciente com náuseas, vômitos e diarreia há 48 horas. Sinais de desidratação leve. Prescrito hidratação oral, antitérmicos e repouso. Orientações sobre dieta leve.',
    fullReportText: `Paciente: José Oliveira (SUS-2C5-E6F)\nData: 2024-07-27\nGravidade: Média\nDiagnóstico: Gastroenterite Viral\nObservações: Paciente, 42 anos, masculino, relata início súbito de vômitos e diarreia aquosa. Apresenta febre e mialgia. Ao exame, mucosas secas e dor abdominal difusa à palpação.\nSinais Vitais: FC: 95 bpm, PA: 110/70 mmHg, Temp: 38.5°C, SpO2: 98%.\nPlano de Tratamento: Recomendado soro de reidratação oral, Dipirona 500mg se febre > 37.8°C. Dieta leve, evitando laticínios e alimentos gordurosos. Repouso. Retornar se houver piora dos sintomas ou incapacidade de se hidratar.`,
  },
  {
    id: 'rep_004',
    patientName: 'Mariana Santos',
    patientId: 'SUS-0A0-A0A',
    date: '2024-07-26',
    severity: 'Baixa',
    diagnosis: 'Check-up de Rotina',
    vitals: {
      'Frequência Cardíaca': '68 bpm',
      'Pressão Arterial': '120/80 mmHg',
      'Temperatura Corporal': '36.5°C',
      'Saturação de Oxigênio': '99%',
    },
    treatmentNotes: 'Paciente assintomática, veio para consulta de rotina. Exames laboratoriais dentro da normalidade. Pressão arterial controlada. Nenhuma nova prescrição necessária.',
    fullReportText: `Paciente: Mariana Santos (SUS-0A0-A0A)\nData: 2024-07-26\nGravidade: Baixa\nDiagnóstico: Check-up de Rotina\nObservações: Paciente, 35 anos, feminina, comparece para avaliação de saúde anual. Nenhuma queixa ativa. Histórico de hipertensão leve, bem controlada com medicação.\nSinais Vitais: FC: 68 bpm, PA: 120/80 mmHg, Temp: 36.5°C, SpO2: 99%.\nPlano de Tratamento: Exames de sangue de rotina (hemograma, glicemia, perfil lipídico) sem alterações significativas. Mantida a prescrição atual de Losartana 50mg/dia. Orientada a manter dieta saudável e atividade física regular. Retorno em 1 ano.`,
  },
];
